CREATE TABLE accounts (
    id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL UNIQUE,
    password VARCHAR NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT NOW(),
    status SMALLINT NOT NULL DEFAULT 0
);